### PR TITLE
Set extend module to dependencies

### PR DESCRIPTION
**Pull request by sapics**
I guess that this PR would fix the Travis error in paperjs (nodejs v4)
https://travis-ci.org/paperjs/paper.js/jobs/157920841

### CODE REVIEW

**Comment by lehni** [comment]
Let's try it and see! Weird that it didn't cause problems earlier though?

**Comment by lehni** [comment]
Alright, that was indeed the reason. Thanks @sapics! Publishing a new version now.

**Comment by sapics** [comment]
It's my pleasure!
I guess that Travis error would come from the version up of `npm` which updates automatically with `nodejs` version up.

**Comment by lehni** [comment]
Could be... It's weird though that with v4.4.7, it wasn't complaining?!

**Pull request merged**
